//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Центр_занятости
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExpWorkUnemployed
    {
        public int ID { get; set; }
        public int ID_Applicant { get; set; }
        public string NameOrg { get; set; }
        public System.DateTime DateStart { get; set; }
        public string OfficialDuties { get; set; }
        public Nullable<System.DateTime> DateOfDismissal { get; set; }
    
        public virtual Applicants Applicants { get; set; }
    }
}
