//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Центр_занятости
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CenterEntities : DbContext
    {
        public CenterEntities()
            : base("name=CenterEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Applicants> Applicants { get; set; }
        public virtual DbSet<ApplicationOfUnemployed> ApplicationOfUnemployed { get; set; }
        public virtual DbSet<Centers> Centers { get; set; }
        public virtual DbSet<Countries> Countries { get; set; }
        public virtual DbSet<Educations> Educations { get; set; }
        public virtual DbSet<ExpWorkType> ExpWorkType { get; set; }
        public virtual DbSet<ExpWorkUnemployed> ExpWorkUnemployed { get; set; }
        public virtual DbSet<Genders> Genders { get; set; }
        public virtual DbSet<Localities> Localities { get; set; }
        public virtual DbSet<ManagerOrg> ManagerOrg { get; set; }
        public virtual DbSet<Organization> Organization { get; set; }
        public virtual DbSet<Passport> Passport { get; set; }
        public virtual DbSet<PaymentAccount> PaymentAccount { get; set; }
        public virtual DbSet<Professions> Professions { get; set; }
        public virtual DbSet<ReferralToWork> ReferralToWork { get; set; }
        public virtual DbSet<Regions> Regions { get; set; }
        public virtual DbSet<RegistrationAddress> RegistrationAddress { get; set; }
        public virtual DbSet<RegistrationOfResidence> RegistrationOfResidence { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<StatusUnemployed> StatusUnemployed { get; set; }
        public virtual DbSet<Stipend> Stipend { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TypeOfEmployment> TypeOfEmployment { get; set; }
        public virtual DbSet<TypeOrganization> TypeOrganization { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<Vacancy> Vacancy { get; set; }
        public virtual DbSet<Workers> Workers { get; set; }
        public virtual DbSet<WorkSchedule> WorkSchedule { get; set; }
    }
}
