//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Центр_занятости
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReferralToWork
    {
        public int ID { get; set; }
        public int ID_Worker { get; set; }
        public int ID_Vacancy { get; set; }
        public int ID_Org { get; set; }
        public int ID_Applicant { get; set; }
        public System.DateTime DateStart { get; set; }
        public System.DateTime DateFinish { get; set; }
        public Nullable<bool> Hired { get; set; }
    
        public virtual Applicants Applicants { get; set; }
        public virtual Organization Organization { get; set; }
        public virtual Vacancy Vacancy { get; set; }
        public virtual Workers Workers { get; set; }
    }
}
