//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Центр_занятости
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stipend
    {
        public int ID { get; set; }
        public int ID_Worker { get; set; }
        public int ID_Applicants { get; set; }
        public System.DateTime DateStipend { get; set; }
        public System.DateTime DateStart { get; set; }
        public System.DateTime DateFinish { get; set; }
        public decimal Payment { get; set; }

        public string Month
        {
            get
            {
                TimeSpan ts = DateFinish - DateStart;
                int m = ts.Days / 28;
                if (m == 1)
                {
                    return $"{m} месяц";
                }
                else if (m > 1 && m <= 4)
                {
                    return $"{m} месяца";
                }
                else return $"{m} месяцев";
            }
        }

        public int Mont
        {
            get
            {
                TimeSpan ts = DateFinish - DateStart;
                int m = ts.Days / 28;
                return m;
            }
        }

        public virtual Applicants Applicants { get; set; }
        public virtual Workers Workers { get; set; }
    }
}
