//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Центр_занятости
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vacancy
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vacancy()
        {
            this.ReferralToWork = new HashSet<ReferralToWork>();
        }
    
        public int ID { get; set; }
        public int ID_Org { get; set; }
        public string Header { get; set; }
        public int Specialization { get; set; }
        public decimal Wages { get; set; }
        public Nullable<int> Region { get; set; }
        public int TypeOfEmployemnt { get; set; }
        public int WorkSchedule { get; set; }
        public int ExpWork { get; set; }
        public int Education { get; set; }
        public bool ForDisabled { get; set; }
        public string Description { get; set; }
        public System.DateTime Date { get; set; }
        public bool Valid { get; set; }
    
        public virtual Educations Educations { get; set; }
        public virtual ExpWorkType ExpWorkType { get; set; }
        public virtual Organization Organization { get; set; }
        public virtual Professions Professions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReferralToWork> ReferralToWork { get; set; }
        public virtual Regions Regions { get; set; }
        public virtual TypeOfEmployment TypeOfEmployment { get; set; }
        public virtual WorkSchedule WorkSchedule1 { get; set; }
    }
}
