//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Центр_занятости
{
    using System;
    using System.Collections.Generic;
    
    public partial class Workers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Workers()
        {
            this.ApplicationOfUnemployed = new HashSet<ApplicationOfUnemployed>();
            this.ReferralToWork = new HashSet<ReferralToWork>();
            this.Stipend = new HashSet<Stipend>();
        }
    
        public int ID { get; set; }
        public int ID_User { get; set; }
        public int ID_Center { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string Patronymic { get; set; }
        public int Gender { get; set; }
        public System.DateTime Birthday { get; set; }
        public decimal Wages { get; set; }

        public string FIO
        {
            get
            {
                return $"{LastName} {FirstName} {Patronymic}";
            }
        }

        public string AbbFIO
        {
            get
            {
                char I = FirstName[0];
                char O = Patronymic[0];
                return $"{LastName} {I}.{O}.";
            }
        }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ApplicationOfUnemployed> ApplicationOfUnemployed { get; set; }
        public virtual Centers Centers { get; set; }
        public virtual Genders Genders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReferralToWork> ReferralToWork { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Stipend> Stipend { get; set; }
        public virtual Users Users { get; set; }
    }
}
